### ISSUE TITLE
Workload: Schedule Payout

### ISSUE THREAD

**Issue by mikekenneth** [PythonBenin/kkiapay-python#3]
**Workload: Schedule Payout**
We will be working on this part of the project at first.
Thanks.

**Comment by nioperas06** [comment]
👍

**Comment by nioperas06** [comment]
@sphinxxanxus

**Comment by sphinxxanxus** [comment]
@mikekenneth @nioperas06  je suis la

**Comment by nioperas06** [comment]
Je me suis rendu compte que dans la vidéo, je ne montrais pas l'interface de Postman. Anyway, je pose ça ici:
![Uploading Postman.png…]()

**Comment by nioperas06** [comment]
Just a friendly reminder :smile:

**Comment by nioperas06** [comment]
I need to create a new version for this package and publish it to pypi
