### ISSUE TITLE
Workload: Exceptions

### ISSUE THREAD

**Issue by OthnielDona** [PythonBenin/kkiapay-python#4]
Je vais prendre les taureaux 🐂 par les cornes.

**Comment by OthnielDona** [comment]
After analysis, I don't think we need to write custom Exception. So far, the only thing that will raise Exceptions is `request` which already has well defined Exception. And if I'm right, the purpose of Exceptions is to allow the user of the package 📦 decide how his program will deal with errors.

Thoughts 💭...

**Comment by nioperas06** [comment]
Crées un compte sandbox et fais un paiement. Ensuite, vérifies le statut de la transaction. Coupe ta connexion internet. Et vérifies le statut encore. Remaques?

**Comment by OthnielDona** [comment]
Il suffit juste de remplace:
```python
transaction = k.verify_transaction('LVFNrK1nx')
print(transaction)
```
avec:

```python
try:
    transaction = k.verify_transaction('LVFNrK1nx')
    print(transaction)
except exceptions.ConnectionError:
    print('There is a problem with your connection')
except exceptions.RequestException as msg:
    print('Something when wrong.')
    print()
    print(msg)
```
et le problem est regler.

**Comment by nioperas06** [comment]
I hate `try/catch` :smile

**Comment by sphinxxanxus** [comment]
@OthnielDona va voir leur php-sdk tu vas voir il y a des status code. Si tu juges toujours inutile les custom exceptions alors c'est cool

**Comment by nioperas06** [comment]
@OthnielDona tu peux rajouter un exemple de code dans le readme pour illustration.

**Comment by sphinxxanxus** [comment]
Anyway je crois que c'est utile. J'en ai fait 2 moi pour le stetup_payout

**Comment by sphinxxanxus** [comment]
@nioperas06 close the issue please
