### ISSUE TITLE
Feature Request: Refund Transaction

### ISSUE THREAD

**Issue by nioperas06** [PythonBenin/kkiapay-python#5]
```python
from kkiapay import Kkiapay

k = Kkiapay('public_key', 'private_key', 'secret', sandbox=True)

transaction = k.refund_transaction('LVFNrK1nx')
```

**Comment by ChafikHadjAbdouRazack** [comment]
@nioperas06 qu'est ce qu'il y a à faire là?

**Comment by nioperas06** [comment]
C'est d'implémenter et de tester la fonctionnalité `refund_transaction` et surtout à voir ce que la requête retourne comme résultat.

**Comment by ChafikHadjAbdouRazack** [comment]
@nioperas06 OK.

**Comment by ChafikHadjAbdouRazack** [comment]
Mais sauf erreur de ma part la fonctionnalité a déjà été implémentée.

**Comment by nioperas06** [comment]
Pas vraiment. On doit simuler réellement cette fonctionnalité et voir si le montant est réellement remboursé.

**Comment by ChafikHadjAbdouRazack** [comment]
Ah d'accord.

**Comment by nioperas06** [comment]
Refund transaction is only available in `live` environment. 🤔
